runtime: java8
inbound_services:
- warmup
derived_file_type:
- java_precompiled
threadsafe: True
auto_id_policy: default
beta_settings:
  'source_reference': 'https://github.com/Hardik-Arora/GCP_Track4.git#1bb5388fce3e995169ba5d77ab7f0fc35cb24f98'
api_version: 'user_defined'
handlers:
- url: /.*
  script: unused
  login: optional
  secure: optional

skip_files: app.yaml
